// Sélection éditoriale "Les 100" — 1990 → 2026.
// `wiki` = titre exact de l'article Wikipédia anglais. Il sert à résoudre l'entité
// Wikidata, qui fournit ensuite l'ID TMDB exact (donc aucune recherche floue).
// `genres` n'est qu'un repli si la source de données n'en renvoie pas.
export const MOVIES = [
  { wiki: 'The Shawshank Redemption', year: 1994, genres: ['Drame', 'Crime'] },
  { wiki: 'Pulp Fiction', year: 1994, genres: ['Crime', 'Thriller'] },
  { wiki: "Schindler's List", year: 1993, genres: ['Drame', 'Histoire', 'Guerre'] },
  { wiki: 'Goodfellas', year: 1990, genres: ['Crime', 'Drame'] },
  { wiki: 'The Silence of the Lambs (film)', year: 1991, genres: ['Thriller', 'Crime', 'Horreur'] },
  { wiki: 'The Matrix', year: 1999, genres: ['Science-Fiction', 'Action'] },
  { wiki: 'Fight Club', year: 1999, genres: ['Drame', 'Thriller'] },
  { wiki: 'Seven (1995 film)', year: 1995, genres: ['Thriller', 'Crime', 'Mystère'] },
  { wiki: 'Jurassic Park (film)', year: 1993, genres: ['Aventure', 'Science-Fiction'] },
  { wiki: 'Terminator 2: Judgment Day', year: 1991, genres: ['Action', 'Science-Fiction'] },
  { wiki: 'Forrest Gump', year: 1994, genres: ['Drame', 'Romance'] },
  { wiki: 'Saving Private Ryan', year: 1998, genres: ['Guerre', 'Drame', 'Action'] },
  { wiki: 'Heat (1995 film)', year: 1995, genres: ['Crime', 'Thriller', 'Action'] },
  { wiki: 'The Truman Show', year: 1998, genres: ['Comédie', 'Drame', 'Science-Fiction'] },
  { wiki: 'The Lion King', year: 1994, genres: ['Animation', 'Familial', 'Drame'] },
  { wiki: 'Toy Story', year: 1995, genres: ['Animation', 'Familial', 'Aventure'] },
  { wiki: 'La Haine', year: 1995, genres: ['Drame', 'Crime'] },
  { wiki: 'Fargo (1996 film)', year: 1996, genres: ['Crime', 'Thriller', 'Comédie'] },
  { wiki: 'Titanic (1997 film)', year: 1997, genres: ['Drame', 'Romance'] },
  { wiki: 'Princess Mononoke', year: 1997, genres: ['Animation', 'Fantastique', 'Aventure'] },
  { wiki: 'Life Is Beautiful', year: 1997, genres: ['Drame', 'Comédie', 'Guerre'] },
  { wiki: 'Reservoir Dogs', year: 1992, genres: ['Crime', 'Thriller'] },
  { wiki: 'Unforgiven', year: 1992, genres: ['Western', 'Drame'] },
  { wiki: 'Groundhog Day (film)', year: 1993, genres: ['Comédie', 'Fantastique', 'Romance'] },
  { wiki: 'Trainspotting (film)', year: 1996, genres: ['Drame', 'Crime'] },
  { wiki: 'Gladiator (2000 film)', year: 2000, genres: ['Action', 'Drame', 'Aventure'] },
  { wiki: 'Memento (film)', year: 2000, genres: ['Thriller', 'Mystère'] },
  { wiki: 'Requiem for a Dream', year: 2000, genres: ['Drame'] },
  { wiki: 'Crouching Tiger, Hidden Dragon', year: 2000, genres: ['Action', 'Aventure', 'Drame'] },
  { wiki: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001, genres: ['Fantastique', 'Aventure', 'Action'] },
  { wiki: 'Spirited Away', year: 2001, genres: ['Animation', 'Fantastique', 'Familial'] },
  { wiki: 'Mulholland Drive (film)', year: 2001, genres: ['Mystère', 'Thriller', 'Drame'] },
  { wiki: 'Amélie', year: 2001, genres: ['Comédie', 'Romance'] },
  { wiki: 'The Lord of the Rings: The Two Towers', year: 2002, genres: ['Fantastique', 'Aventure', 'Action'] },
  { wiki: 'City of God (2002 film)', year: 2002, genres: ['Crime', 'Drame'] },
  { wiki: 'The Pianist (2002 film)', year: 2002, genres: ['Drame', 'Guerre', 'Histoire'] },
  { wiki: 'The Lord of the Rings: The Return of the King', year: 2003, genres: ['Fantastique', 'Aventure', 'Action'] },
  { wiki: 'Oldboy (2003 film)', year: 2003, genres: ['Thriller', 'Drame', 'Mystère'] },
  { wiki: 'Kill Bill: Volume 1', year: 2003, genres: ['Action', 'Crime', 'Thriller'] },
  { wiki: 'Eternal Sunshine of the Spotless Mind', year: 2004, genres: ['Romance', 'Drame', 'Science-Fiction'] },
  { wiki: 'The Incredibles', year: 2004, genres: ['Animation', 'Action', 'Familial'] },
  { wiki: 'Brokeback Mountain', year: 2005, genres: ['Drame', 'Romance'] },
  { wiki: "Pan's Labyrinth", year: 2006, genres: ['Fantastique', 'Drame', 'Guerre'] },
  { wiki: 'The Departed', year: 2006, genres: ['Crime', 'Thriller', 'Drame'] },
  { wiki: 'Children of Men', year: 2006, genres: ['Science-Fiction', 'Thriller', 'Drame'] },
  { wiki: 'The Prestige (film)', year: 2006, genres: ['Mystère', 'Thriller', 'Drame'] },
  { wiki: 'No Country for Old Men', year: 2007, genres: ['Thriller', 'Crime', 'Drame'] },
  { wiki: 'There Will Be Blood', year: 2007, genres: ['Drame', 'Histoire'] },
  { wiki: 'The Dark Knight', year: 2008, genres: ['Action', 'Crime', 'Thriller'] },
  { wiki: 'Inglourious Basterds', year: 2009, genres: ['Guerre', 'Drame', 'Aventure'] },
  { wiki: 'Inception', year: 2010, genres: ['Science-Fiction', 'Action', 'Thriller'] },
  { wiki: 'The Social Network', year: 2010, genres: ['Drame'] },
  { wiki: 'Black Swan (film)', year: 2010, genres: ['Drame', 'Thriller'] },
  { wiki: 'Drive (2011 film)', year: 2011, genres: ['Crime', 'Thriller', 'Drame'] },
  { wiki: 'The Intouchables', year: 2011, genres: ['Comédie', 'Drame'] },
  { wiki: 'A Separation', year: 2011, genres: ['Drame'] },
  { wiki: 'Django Unchained', year: 2012, genres: ['Western', 'Drame'] },
  { wiki: 'The Hunt (2012 film)', year: 2012, genres: ['Drame'] },
  { wiki: 'Her (2013 film)', year: 2013, genres: ['Romance', 'Drame', 'Science-Fiction'] },
  { wiki: 'Prisoners (2013 film)', year: 2013, genres: ['Thriller', 'Drame', 'Crime'] },
  { wiki: 'The Wolf of Wall Street (2013 film)', year: 2013, genres: ['Crime', 'Drame', 'Comédie'] },
  { wiki: '12 Years a Slave (film)', year: 2013, genres: ['Drame', 'Histoire'] },
  { wiki: 'Interstellar (film)', year: 2014, genres: ['Science-Fiction', 'Aventure', 'Drame'] },
  { wiki: 'Whiplash (2014 film)', year: 2014, genres: ['Drame', 'Musique'] },
  { wiki: 'Gone Girl (film)', year: 2014, genres: ['Thriller', 'Mystère', 'Drame'] },
  { wiki: 'The Grand Budapest Hotel', year: 2014, genres: ['Comédie', 'Aventure'] },
  { wiki: 'Mad Max: Fury Road', year: 2015, genres: ['Action', 'Aventure', 'Science-Fiction'] },
  { wiki: 'Inside Out (2015 film)', year: 2015, genres: ['Animation', 'Familial', 'Aventure'] },
  { wiki: 'Spotlight (film)', year: 2015, genres: ['Drame', 'Histoire'] },
  { wiki: 'Arrival (film)', year: 2016, genres: ['Science-Fiction', 'Drame', 'Mystère'] },
  { wiki: 'La La Land', year: 2016, genres: ['Romance', 'Musique', 'Drame'] },
  { wiki: 'Moonlight (2016 film)', year: 2016, genres: ['Drame'] },
  { wiki: 'Your Name', year: 2016, genres: ['Animation', 'Romance', 'Fantastique'] },
  { wiki: 'Get Out', year: 2017, genres: ['Horreur', 'Thriller', 'Mystère'] },
  { wiki: 'Blade Runner 2049', year: 2017, genres: ['Science-Fiction', 'Drame', 'Mystère'] },
  { wiki: 'Coco (2017 film)', year: 2017, genres: ['Animation', 'Familial', 'Aventure'] },
  { wiki: 'Spider-Man: Into the Spider-Verse', year: 2018, genres: ['Animation', 'Action', 'Aventure'] },
  { wiki: 'Parasite (2019 film)', year: 2019, genres: ['Thriller', 'Drame', 'Comédie'] },
  { wiki: 'Joker (2019 film)', year: 2019, genres: ['Drame', 'Crime', 'Thriller'] },
  { wiki: '1917 (2019 film)', year: 2019, genres: ['Guerre', 'Drame', 'Action'] },
  { wiki: 'The Father (2020 film)', year: 2020, genres: ['Drame'] },
  { wiki: 'Another Round (film)', year: 2020, genres: ['Drame', 'Comédie'] },
  { wiki: 'Soul (2020 film)', year: 2020, genres: ['Animation', 'Familial', 'Comédie'] },
  { wiki: 'Dune (2021 film)', year: 2021, genres: ['Science-Fiction', 'Aventure'] },
  { wiki: 'Everything Everywhere All at Once', year: 2022, genres: ['Action', 'Aventure', 'Science-Fiction'] },
  { wiki: 'Top Gun: Maverick', year: 2022, genres: ['Action', 'Drame'] },
  { wiki: 'The Batman (film)', year: 2022, genres: ['Action', 'Crime', 'Mystère'] },
  { wiki: 'Aftersun', year: 2022, genres: ['Drame'] },
  { wiki: 'All Quiet on the Western Front (2022 film)', year: 2022, genres: ['Guerre', 'Drame', 'Action'] },
  { wiki: 'Oppenheimer (film)', year: 2023, genres: ['Drame', 'Histoire'] },
  { wiki: 'Past Lives (film)', year: 2023, genres: ['Romance', 'Drame'] },
  { wiki: 'Anatomy of a Fall', year: 2023, genres: ['Thriller', 'Drame', 'Crime'] },
  { wiki: 'The Holdovers', year: 2023, genres: ['Comédie', 'Drame'] },
  { wiki: 'Spider-Man: Across the Spider-Verse', year: 2023, genres: ['Animation', 'Action', 'Aventure'] },
  { wiki: 'Dune: Part Two', year: 2024, genres: ['Science-Fiction', 'Aventure'] },
  { wiki: 'Anora', year: 2024, genres: ['Drame', 'Comédie', 'Romance'] },
  { wiki: 'The Substance', year: 2024, genres: ['Horreur', 'Science-Fiction', 'Drame'] },
  { wiki: 'Sinners (2025 film)', year: 2025, genres: ['Horreur', 'Thriller'] },
  { wiki: 'One Battle After Another', year: 2025, genres: ['Comédie', 'Action', 'Thriller'] },
  { wiki: 'The Odyssey (2026 film)', year: 2026, genres: ['Aventure', 'Fantastique', 'Action'] },
]
