// Humeurs — annotation éditoriale, assumée comme telle.
//
// Aucune base de données ne fournit « mindfuck » ou « facile à regarder » :
// ces étiquettes sont un jugement, pas une donnée. Elles vivent donc ici,
// à côté de la sélection, et survivent à toute régénération depuis TMDB.
//
// Vocabulaire volontairement court : au-delà d'une dizaine d'humeurs, plus
// personne ne sait laquelle choisir en moins de 15 secondes.
export const MOOD_IDS = [
  'drole',
  'intense',
  'facile',
  'mindfuck',
  'emotion',
  'stressant',
  'spectaculaire',
  'intelligent',
  'chill',
  'surprenant',
]

/** Clé = titre d'article Wikipédia EN, comme dans movies.seed.mjs. */
export const MOODS = {
  'The Shawshank Redemption': ['emotion', 'intelligent'],
  'Pulp Fiction': ['surprenant', 'intelligent', 'drole'],
  "Schindler's List": ['emotion', 'intense'],
  Goodfellas: ['intense', 'intelligent'],
  'The Silence of the Lambs (film)': ['stressant', 'intense', 'intelligent'],
  'The Matrix': ['spectaculaire', 'mindfuck', 'intense'],
  'Fight Club': ['mindfuck', 'intense', 'intelligent'],
  'Seven (1995 film)': ['stressant', 'intense'],
  'Jurassic Park (film)': ['spectaculaire', 'intense', 'facile'],
  'Terminator 2: Judgment Day': ['spectaculaire', 'intense'],
  'Forrest Gump': ['emotion', 'facile'],
  'Saving Private Ryan': ['intense', 'emotion', 'spectaculaire'],
  'Heat (1995 film)': ['intense', 'intelligent'],
  'The Truman Show': ['intelligent', 'emotion', 'surprenant'],
  'The Lion King': ['emotion', 'facile'],
  'Toy Story': ['facile', 'drole', 'emotion'],
  'La Haine': ['intense', 'intelligent'],
  'Fargo (1996 film)': ['drole', 'surprenant', 'intelligent'],
  'Titanic (1997 film)': ['emotion', 'spectaculaire'],
  'Princess Mononoke': ['spectaculaire', 'emotion', 'intelligent'],
  'Life Is Beautiful': ['emotion', 'drole'],
  'Reservoir Dogs': ['intense', 'stressant'],
  Unforgiven: ['intense', 'intelligent'],
  'Groundhog Day (film)': ['drole', 'facile', 'intelligent'],
  'Trainspotting (film)': ['intense', 'surprenant', 'drole'],
  'Gladiator (2000 film)': ['spectaculaire', 'intense', 'emotion'],
  'Memento (film)': ['mindfuck', 'intelligent'],
  'Requiem for a Dream': ['intense', 'stressant', 'emotion'],
  'Crouching Tiger, Hidden Dragon': ['spectaculaire', 'emotion'],
  'The Lord of the Rings: The Fellowship of the Ring': ['spectaculaire', 'emotion'],
  'Spirited Away': ['surprenant', 'emotion', 'chill'],
  'Mulholland Drive (film)': ['mindfuck', 'stressant'],
  'Amélie': ['facile', 'chill', 'emotion'],
  'The Lord of the Rings: The Two Towers': ['spectaculaire', 'intense'],
  'City of God (2002 film)': ['intense', 'stressant'],
  'The Pianist (2002 film)': ['emotion', 'intense'],
  'The Lord of the Rings: The Return of the King': ['spectaculaire', 'emotion'],
  'Oldboy (2003 film)': ['mindfuck', 'intense', 'stressant'],
  'Kill Bill: Volume 1': ['spectaculaire', 'intense', 'surprenant'],
  'Eternal Sunshine of the Spotless Mind': ['emotion', 'mindfuck', 'intelligent'],
  'The Incredibles': ['drole', 'spectaculaire', 'facile'],
  'Brokeback Mountain': ['emotion', 'chill'],
  "Pan's Labyrinth": ['emotion', 'stressant', 'surprenant'],
  'The Departed': ['intense', 'stressant'],
  'Children of Men': ['intense', 'stressant', 'intelligent'],
  'The Prestige (film)': ['mindfuck', 'intelligent', 'surprenant'],
  'No Country for Old Men': ['stressant', 'intense', 'intelligent'],
  'There Will Be Blood': ['intense', 'intelligent'],
  'The Dark Knight': ['spectaculaire', 'intense'],
  'Inglourious Basterds': ['intense', 'drole', 'surprenant'],
  Inception: ['mindfuck', 'spectaculaire', 'intelligent'],
  'The Social Network': ['intelligent', 'intense'],
  'Black Swan (film)': ['stressant', 'intense', 'mindfuck'],
  'Drive (2011 film)': ['intense', 'chill', 'stressant'],
  'The Intouchables': ['drole', 'emotion', 'facile'],
  'A Separation': ['intense', 'intelligent', 'emotion'],
  'Django Unchained': ['intense', 'drole', 'spectaculaire'],
  'The Hunt (2012 film)': ['stressant', 'intense', 'emotion'],
  'Her (2013 film)': ['emotion', 'chill', 'intelligent'],
  'Prisoners (2013 film)': ['stressant', 'intense'],
  'The Wolf of Wall Street (2013 film)': ['drole', 'intense', 'spectaculaire'],
  '12 Years a Slave (film)': ['emotion', 'intense'],
  'Interstellar (film)': ['spectaculaire', 'emotion', 'mindfuck'],
  'Whiplash (2014 film)': ['intense', 'stressant'],
  'Gone Girl (film)': ['surprenant', 'stressant', 'intelligent'],
  'The Grand Budapest Hotel': ['drole', 'facile', 'chill'],
  'Mad Max: Fury Road': ['spectaculaire', 'intense'],
  'Inside Out (2015 film)': ['emotion', 'drole', 'facile'],
  'Spotlight (film)': ['intelligent', 'intense'],
  'Arrival (film)': ['intelligent', 'emotion', 'mindfuck'],
  'La La Land': ['emotion', 'chill', 'facile'],
  'Moonlight (2016 film)': ['emotion', 'chill'],
  'Your Name': ['emotion', 'surprenant', 'chill'],
  'Get Out': ['stressant', 'surprenant', 'intelligent'],
  'Blade Runner 2049': ['spectaculaire', 'chill', 'intelligent'],
  'Coco (2017 film)': ['emotion', 'facile', 'spectaculaire'],
  'Spider-Man: Into the Spider-Verse': ['spectaculaire', 'drole', 'emotion'],
  'Parasite (2019 film)': ['surprenant', 'stressant', 'intelligent'],
  'Joker (2019 film)': ['intense', 'stressant'],
  '1917 (2019 film)': ['intense', 'spectaculaire', 'stressant'],
  'The Father (2020 film)': ['emotion', 'mindfuck', 'stressant'],
  'Another Round (film)': ['drole', 'emotion', 'intelligent'],
  'Soul (2020 film)': ['emotion', 'chill', 'intelligent'],
  'Dune (2021 film)': ['spectaculaire', 'chill', 'intelligent'],
  'Everything Everywhere All at Once': ['mindfuck', 'drole', 'emotion'],
  'Top Gun: Maverick': ['spectaculaire', 'intense', 'facile'],
  'The Batman (film)': ['intense', 'stressant', 'spectaculaire'],
  Aftersun: ['emotion', 'chill'],
  'All Quiet on the Western Front (2022 film)': ['intense', 'stressant', 'emotion'],
  'Oppenheimer (film)': ['intense', 'intelligent'],
  'Past Lives (film)': ['emotion', 'chill'],
  'Anatomy of a Fall': ['intelligent', 'stressant'],
  'The Holdovers': ['drole', 'emotion', 'chill'],
  'Spider-Man: Across the Spider-Verse': ['spectaculaire', 'mindfuck', 'emotion'],
  'Dune: Part Two': ['spectaculaire', 'intense'],
  Anora: ['drole', 'intense', 'emotion'],
  'The Substance': ['stressant', 'mindfuck', 'surprenant'],
  'Sinners (2025 film)': ['stressant', 'spectaculaire', 'intense'],
  'One Battle After Another': ['drole', 'intense', 'surprenant'],
  'The Odyssey (2026 film)': ['spectaculaire', 'intense'],
}
